# Site settings
author: T Perez
title: Student Blog
header-img: img/home-bg.png
email: thuante88@gmail.com
copyright_name: T Perez
description: > # this means to ignore newlines until "baseurl:"
  for Flatiron
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  thuante88

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
